[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    
[[plugins]]
package = "netlify-plugin-inline-functions-env"

